[package]
name = "available-enis"
version = "0.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Count and optionally delete available AWS Elastic Networks"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aws-config = "1.0.0"
aws-types = "1.0.0"
aws-sdk-ec2 = "0.39.1"
futures = "0.3.29"
tracing = "0.1.40"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3.18"

[dependencies.clap]
features = ["derive", "wrap_help"]
version = "4.4.8"

[dependencies.tokio]
version = "1.34.0"
features = ["macros", "rt-multi-thread"]
