[package]
name = "available-enis"
version = "0.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Count and optionally delete available AWS Elastic Networks"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
aws-config = "0.55.1"
aws-types = "0.55.1"
aws-sdk-ec2 = "0.26.0"
futures = "0.3.28"
tracing = "0.1.37"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3.16"

[dependencies.clap]
features = ["derive", "wrap_help"]
version = "4.2.2"

[dependencies.tokio]
version = "1.27.0"
features = ["macros", "rt-multi-thread"]
