[package]
name = "available-enis"
version = "0.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Count and optionally delete available AWS Elastic Networks"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
aws-config = "0.53.0"
aws-types = "0.53.0"
aws-sdk-ec2 = "0.23.0"
futures = "0.3.25"
tracing = "0.1.37"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3.1"

[dependencies.clap]
features = ["derive", "wrap_help"]
version = "4.1.1"

[dependencies.tokio]
version = "1.24.2"
features = ["macros", "rt-multi-thread"]
